### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by linrl3** [nhorman/dropwatch#39]
```
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
main.c:23:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
Makefile:422: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
```

Got this error when I run make. Does anyone know how I could solve this?

**Comment by nhorman** [comment]
you need to have the libreadline development libraries installed.  We do a pkg-config check for them, but the error case just adds the library linker option in because it wasnt until recently that the readline .pc file was included.  I can change that, but the change will just update the error above to fail during configure, indicating that you need the readline-devel package

**Comment by linrl3** [comment]
@nhorman Got it! Thanks!!

**Comment by slavitch** [comment]
I get libreadline is required even if libreadline7 is installed.

**Comment by slavitch** [comment]
This is ubuntu 18.04

**Comment by nhorman** [comment]
https://bugs.launchpad.net/ubuntu/+source/readline/+bug/1938591
