### ISSUE TITLE
Cannot find readline lib

### ISSUE THREAD

**Issue by oscarkramer** [nhorman/dropwatch#42]
After running ./autogen.sh, the ./configure step is complaining about libreadline:
```
checking for READLINE... no
configure: error: libreadline is required
```
However, I do have that package installed (v7). I installed it successfully with apt. From apt list, I see
```
libreadline-dev/bionic,now 7.0-3 amd64 [installed]
```
I can see libreadline.so and the include directory under /usr/lib/x86_64-linux-gnu and /usr/include, respectively. 

Any ideas how I can get configure to see the installl? I'm on Ubuntu 18.04

Thanks

**Comment by nhorman** [comment]
What version of debian are you running?  Debian only very recently pulled in the version of libreadline that included the pkg-config file I think

**Comment by oscarkramer** [comment]
There is no readline.pc if that's what you mean. There was some verbage on that in the configure.ac. I'm running Ubuntu 18.04 and it's package manager (apt) pulled down libreadline-7.

**Comment by nhorman** [comment]
yeah, because the debian maintainers never included the .pc file in the package.  Its been there since 2016:
http://git.savannah.gnu.org/cgit/readline.git/log/readline.pc.in

but they didn't include it when they packaged that version and have never fixed it.  At this point we're on to readline-8, and I'm not sure if they've fixed it there yet either.  I kept a fall back condition in place until recently:
https://github.com/nhorman/dropwatch/commit/c18f3d25a94eb72145c663797794d2697a226594

Which causes failures in other places that are hard to deciper if you legitmately don't have readline installed.  at this point I feel like 4 years is long enough to wait to catch up and fix the ubuntu dev package, so I've update my config script to detect packages properly.  The correct fix here is for ubuntu/debian to include the readline.pc file in their libreadline-dev package
