### ISSUE TITLE
Compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by Ataraxxia** [nhorman/dropwatch#52]
Not really an issue but a thing worth having here:

When configuring on Ubuntu 18.04 there is an error about readline library. 

```
checking for READLINE... no
configure: error: libreadline is required
```

It is caused by a lack of a proper definition file so that `./configure` can properly recognize the lib. 

It can be fixed by creating file `/usr/share/pkgconfig/readline.pc` containing:

```
Name: Readline
Description: Gnu Readline library for command line editing
URL: http://tiswww.cwru.edu/php/chet/readline/rltop.html
Version: 7.0
Requires.private: tinfo
Libs: -lreadline
Cflags: -I/usr/include/readline
```

Source:
https://www.marache.net/post/readline-pc.html

**Comment by nhorman** [comment]
Please dont go suggesting that solution, it's wrong.  A proper solution is to go check out the readline git tree from gnu, build and install it.  Its had the readline pkg-config file checked in since 2015.  Better still, open a bug on launchpad telling the ubuntu maintainers to do that.  Theres really no excuse for them to be almost 6 years behind on package updates like this
