### ISSUE TITLE
Debian 10 - libreadline is required

### ISSUE THREAD

**Issue by Supsuop** [nhorman/dropwatch#81]
I am currently trying to install the tool.
However, it stops at the "configure" command.

Error:
~~~
checking for READLINE... no
configure: error: libreadline is required
~~~

I already have installed libreadline-dev even libreadline5 and libreadline7.

Maybe someone can help out.

**Comment by nhorman** [comment]
You can help yourself out, bu checking in with your distro first (though I grant you their not being very helpful about this)

The version of libreadline in buster, and the companion ubuntu 18.01 release is missing a packageconfig file, which makes building applications with it impossible (unless every upstream project wants to hack up their build system).  Upstream fixed this literally more than 3 years ago now, and most distros picked up the fix immediately.  in 2021 I opened a bug with ubuntu:
https://bugs.launchpad.net/ubuntu/+source/readline/+bug/1938591
under the expectation that such an easy fix would be reported upstream and handled quickly.

You see where we are now.

If you want this fixed, join that bug and make noise until they take notice, alternatively, you can get the upstream version of libreadline and build that so that dropwatch can build as well.   I think more recent versions of debian might have a fixed readline as well, but their reputation for keeping packages up to date isn't great in my view right now, so no guarantees
